### ISSUE TITLE
Super Metrics and working version

### ISSUE THREAD

**Issue by jeffreySilverman** [notoriousbdg/vrops-dashboard-cost_showback_using_super_metrics#1]
The description suggests that this dashboard works with vROPS versions 7.5 and 8.x  The super metrics provided references metrics that are not exposed until version 8.   How does this work with version 7.5?

**Comment by notoriousbdg** [comment]
Good point.  I forgot I changed the super metrics to refer to effective cost, which was introduced in 8.0.  As is, it won't work for 7.5.  I've fixed the readme with https://github.com/notoriousbdg/vrops-dashboard-cost_showback_using_super_metrics/commit/87034654314e4fd35c01ee57a7fad4c962ddc20c.

As a workaround, you could change the MTD Effective Total Cost metrics to Cost|MTD Total Cost, but that will only work if you're using utilization based cost.  I strongly recommend upgrading though.

**Comment by jeffreySilverman** [comment]
Much appreciate and trying hard to get up that that version/

**Comment by jeffreySilverman** [comment]
There is one other anomaly maybe you can explain.  The super metrics refer to TIER:Badge Health.  Where does that object come from ? Is that something else that is new to version 8?

**Comment by notoriousbdg** [comment]
Tiers are objects created when you define tiers of an application.  You can create applications at Environment / Applications.
